name: bun-portfolio-standalone
services:
  app:
    image: ghcr.io/tuukkaviitanen/yaml-portfolio:latest
    volumes:
      - ./portfolio.yaml:/app/portfolio.yaml
    env_file:
      - .env
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
