name: bun-portfolio-prod
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./portfolio.yaml:/app/portfolio.yaml
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
