name: bun-portfolio-dev
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./portfolio.yaml:/app/portfolio.yaml
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 3000:3000
